const OPENAI_RESPONSES_URL='https://api.openai.com/v1/responses';

const errorCategories=['meaning_change','omission','addition','particle','verb_conjugation','tense_aspect','word_order','vocabulary_choice','collocation','register','politeness','kanji','kana','punctuation','counter','adjective','relative_clause','condition','literal_translation','unnatural_expression','source_misunderstanding'];
const score={type:'integer',minimum:0,maximum:100};
const stringList={type:'array',items:{type:'string'}};
const errorSchema={type:'object',additionalProperties:false,required:['error_id','category','subtype','severity','source_span','corrected_span','explanation_es','grammar_tags','vocabulary_tags','affects_meaning','affects_comprehensibility','affects_naturalness'],properties:{error_id:{type:'string'},category:{type:'string',enum:errorCategories},subtype:{type:'string'},severity:{type:'string',enum:['minor','major','critical']},source_span:{type:'string'},corrected_span:{type:'string'},explanation_es:{type:'string'},grammar_tags:stringList,vocabulary_tags:stringList,affects_meaning:{type:'boolean'},affects_comprehensibility:{type:'boolean'},affects_naturalness:{type:'boolean'}}};
const evaluationSchema={type:'object',additionalProperties:false,required:['evaluation_status','corrected_answer','natural_answer','objective_score','comprehensibility_score','naturalness_score','grammar_score','vocabulary_score','orthography_score','register_score','overall_score','is_acceptable','meaning_changed','confidence_score','explanation_es','native_interpretation_es','strengths','errors','detected_grammar_tags','detected_vocabulary_tags','detected_error_tags','next_practice_tags'],properties:{evaluation_status:{type:'string',enum:['valid']},corrected_answer:{type:'string'},natural_answer:{type:'string'},objective_score:score,comprehensibility_score:score,naturalness_score:score,grammar_score:score,vocabulary_score:score,orthography_score:score,register_score:score,overall_score:score,is_acceptable:{type:'boolean'},meaning_changed:{type:'boolean'},confidence_score:score,explanation_es:{type:'string'},native_interpretation_es:{type:'string'},strengths:stringList,errors:{type:'array',items:errorSchema},detected_grammar_tags:stringList,detected_vocabulary_tags:stringList,detected_error_tags:stringList,next_practice_tags:stringList}};

function cors(origin,env){const allowed=(env.APP_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);const local=/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin);return allowed.includes(origin)||local?origin:''}
function json(body,status=200,origin='',env={}){const allow=cors(origin,env);return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...(allow?{'Access-Control-Allow-Origin':allow,'Vary':'Origin'}:{})}})}
function systemPrompt(){return `Eres un profesor experto de japonés para hispanohablantes. Evalúa una traducción sin tratar la referencia como única respuesta válida. Distingue error objetivo, alternativa correcta, comprensible pero poco natural, cambio de significado, partículas, conjugación, léxico, registro, ortografía y omisiones aceptables por contexto. Explica en español con precisión y brevedad. Las puntuaciones deben ser coherentes entre sí. overall_score es la media ponderada: objetivo 30%, comprensión 15%, naturalidad 15%, gramática 15%, vocabulario 10%, ortografía 10% y registro 5%. Usa exclusivamente categorías normalizadas del esquema. No inventes errores si la respuesta es válida.`}

async function callOpenAI(payload,env,includeTemperature=true){
  const body={model:'gpt-5.4-mini',reasoning:{effort:'low'},instructions:systemPrompt(),input:JSON.stringify(payload),max_output_tokens:3500,text:{format:{type:'json_schema',name:'japoteacher_evaluation',strict:true,schema:evaluationSchema}}};
  if(includeTemperature)body.temperature=0.2;
  return fetch(OPENAI_RESPONSES_URL,{method:'POST',headers:{'Authorization':`Bearer ${env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});
}

async function authenticated(request,env){
  const authorization=request.headers.get('Authorization')||'';
  const deviceId=request.headers.get('X-Device-ID')||'';
  if(!authorization.startsWith('Bearer ')||authorization.length>4096||!deviceId||deviceId.length>100)return false;
  try{
    const response=await fetch(`${env.SUPABASE_URL}/rest/v1/rpc/heartbeat_user_session`,{method:'POST',headers:{Authorization:authorization,apikey:env.SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({p_device_id:deviceId}),signal:AbortSignal.timeout(5000)});
    return response.ok&&await response.json()===true;
  }catch{return false}
}

export default{async fetch(request,env){const url=new URL(request.url),origin=request.headers.get('Origin')||'';if(request.method==='OPTIONS'){const allow=cors(origin,env);return new Response(null,{status:204,headers:{...(allow?{'Access-Control-Allow-Origin':allow}:{ }),'Access-Control-Allow-Headers':'Authorization, Content-Type, X-Device-ID','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin'}})}if(url.pathname==='/health')return json({ok:true,model:'gpt-5.4-mini'},200,origin,env);if(url.pathname!=='/evaluate'||request.method!=='POST')return json({error:'Not found'},404,origin,env);if(!env.OPENAI_API_KEY||!env.SUPABASE_URL||!env.SUPABASE_PUBLISHABLE_KEY)return json({error:'El Worker no está configurado.'},503,origin,env);if(!cors(origin,env))return json({error:'Origen no permitido.'},403,origin,env);if(!await authenticated(request,env))return json({error:'Esta cuenta está activa en otro dispositivo.'},409,origin,env);
  let payload;try{payload=await request.json()}catch{return json({error:'JSON de entrada inválido.'},400,origin,env)}if(!payload?.exercise?.exercise_id||!payload?.attempt||typeof payload.attempt.user_answer!=='string')return json({error:'Payload incompleto.'},400,origin,env);
  try{let response=await callOpenAI(payload,env,true);let raw=await response.json();if(!response.ok&&(raw?.error?.param==='temperature'||/temperature/i.test(raw?.error?.message||''))){response=await callOpenAI(payload,env,false);raw=await response.json()}if(!response.ok)return json({error:{message:raw?.error?.message||'OpenAI rechazó la solicitud.',type:raw?.error?.type}},response.status,origin,env);let outputText=raw.output_text;if(!outputText)outputText=(raw.output||[]).flatMap(item=>item.content||[]).find(item=>item.type==='output_text')?.text;if(!outputText)return json({error:'OpenAI no devolvió contenido evaluable.'},502,origin,env);const evaluation=JSON.parse(outputText);return json({evaluation,usage:raw.usage,model:raw.model,response_id:raw.id},200,origin,env)}catch(error){return json({error:error.message||'Error interno del Worker.'},500,origin,env)}}};
