(function(){
  const config=window.JAPOTEACHER_SUPABASE;
  const client=window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  let user=null,timer=null,syncing=false;
  const $=s=>document.querySelector(s);
  function status(message,tone=''){const el=$('#cloudStatus');if(el){el.textContent=message;el.dataset.tone=tone}}
  function render(){const signed=Boolean(user);$('#authSignedOut').hidden=signed;$('#authSignedIn').hidden=!signed;if(signed)$('#authUserEmail').textContent=user.email||'Usuario';status(signed?'Sincronización activa':'Inicia sesión para sincronizar')}
  async function push(){if(!user||syncing)return;syncing=true;status('Sincronizando…');try{const payload=await JapoDB.backup();const {error}=await client.from('user_state').upsert({user_id:user.id,payload},{onConflict:'user_id'});if(error)throw error;status(`Sincronizado a las ${new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}`,'ok')}catch(error){status(error.message||'No se pudo sincronizar','error')}finally{syncing=false}}
  function schedule(){if(!user||syncing)return;clearTimeout(timer);timer=setTimeout(push,900)}
  async function reconcile(){if(!user)return;status('Comprobando datos…');const {data,error}=await client.from('user_state').select('payload').eq('user_id',user.id).maybeSingle();if(error)throw error;if(data?.payload){if(sessionStorage.getItem('japoteacher_restored')===user.id){status('Sincronización activa','ok');return}const localSettings=await JapoDB.get('settings','app');syncing=true;await JapoDB.restore(data.payload);if(localSettings?.value?.proxyToken){const restored=await JapoDB.get('settings','app');restored.value.proxyToken=localSettings.value.proxyToken;await JapoDB.put('settings',restored)}syncing=false;sessionStorage.setItem('japoteacher_restored',user.id);status('Progreso recuperado','ok');setTimeout(()=>location.reload(),500)}else await push()}
  async function signUp(){const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||password.length<8){status('Introduce un email y una contraseña de al menos 8 caracteres','error');return}status('Creando cuenta…');const {data,error}=await client.auth.signUp({email,password});if(error){status(error.message,'error');return}if(!data.session)status('Revisa tu email para confirmar la cuenta','ok')}
  async function signIn(){const email=$('#authEmail').value.trim(),password=$('#authPassword').value;status('Iniciando sesión…');const {error}=await client.auth.signInWithPassword({email,password});if(error)status(error.message,'error')}
  async function signOut(){sessionStorage.removeItem('japoteacher_restored');await client.auth.signOut()}
  async function init(){const {data}=await client.auth.getSession();user=data.session?.user||null;render();$('#signUpButton').addEventListener('click',signUp);$('#signInButton').addEventListener('click',signIn);$('#signOutButton').addEventListener('click',signOut);$('#syncNowButton').addEventListener('click',push);client.auth.onAuthStateChange((event,session)=>{const previous=user?.id;user=session?.user||null;render();if(user&&user.id!==previous)setTimeout(()=>reconcile().catch(e=>status(e.message,'error')),0)});if(user)await reconcile()}
  window.CloudSync={schedule,push};document.addEventListener('DOMContentLoaded',()=>init().catch(e=>status(e.message,'error')));
})();
