(function(){
  let snapshot=null,forcedDirection='all';
  const $=s=>document.querySelector(s),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function normalized(attempt){const copy={...attempt};for(const key of ['strengths','errors','kanji_readings','detected_grammar_tags','detected_vocabulary_tags','detected_error_tags','next_practice_tags']){const stored=attempt[`${key}_json`];if(!Array.isArray(copy[key]))try{copy[key]=JSON.parse(stored||'[]')}catch{copy[key]=[]}}return copy}
  function filtered(){const query=$('#historySearch').value.trim().toLowerCase(),direction=forcedDirection==='all'?$('#historyDirection').value:forcedDirection,result=$('#historyResult').value;return snapshot.attempts.filter(a=>{const exercise=snapshot.eMap.get(a.exercise_id),haystack=`${exercise?.source_text||''} ${a.user_answer||''} ${a.natural_answer||''}`.toLowerCase();return(direction==='all'||a.direction===direction)&&(result==='all'||(result==='acceptable'?a.is_acceptable:!a.is_acceptable))&&(!query||haystack.includes(query))})}
  function draw(){if(!snapshot)return;const rows=filtered();$('#historyCount').textContent=`${rows.length} intento${rows.length===1?'':'s'}`;$('#historyTable').innerHTML=rows.map(a=>{const e=snapshot.eMap.get(a.exercise_id);return `<tr class="history-row" tabindex="0" data-attempt-id="${esc(a.attempt_id)}"><td>${new Date(a.attempted_at).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'})}</td><td class="history-source"><strong>${esc(e?.source_text||a.exercise_id)}</strong>${e?Difficulty.html(e):''}</td><td>${UI.directionName(a.direction)}</td><td><strong>${a.overall_score??'—'}%</strong></td><td class="${a.is_acceptable?'status-good':'status-bad'}">${a.is_acceptable?'Aceptable':'Revisar'} →</td></tr>`}).join('')||'<tr><td colspan="5" class="empty">No hay intentos con estos filtros.</td></tr>'}
  function open(id){const attempt=snapshot.attempts.find(a=>a.attempt_id===id),exercise=snapshot.eMap.get(attempt?.exercise_id);if(!attempt)return;const ev=normalized(attempt),body=$('#historyDetailBody');$('#historyDetailTitle').textContent=`Intento del ${new Date(attempt.attempted_at).toLocaleString('es-ES')}`;body.dataset.attemptId=id;body.innerHTML=`<div class="history-question"><span>${UI.directionName(attempt.direction)}</span><strong>${esc(exercise?.source_text||attempt.exercise_id)}</strong>${exercise?Difficulty.html(exercise):''}</div>${UI.feedback(ev,attempt.user_answer,{showNext:false,direction:attempt.direction,exercise})}`;$('#historyDetail').hidden=false;$('#closeHistoryDetail').focus()}
  function render(data,options={}){snapshot=data;forcedDirection=options.direction||'all';const control=$('#historyDirection');control.value=forcedDirection;control.disabled=forcedDirection!=='all';draw()}
  document.addEventListener('DOMContentLoaded',()=>{$('#historySearch').addEventListener('input',draw);$('#historyDirection').addEventListener('change',draw);$('#historyResult').addEventListener('change',draw);$('#historyTable').addEventListener('click',e=>{const row=e.target.closest('[data-attempt-id]');if(row)open(row.dataset.attemptId)});$('#historyTable').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-attempt-id]'))open(e.target.dataset.attemptId)});$('#closeHistoryDetail').addEventListener('click',()=>$('#historyDetail').hidden=true);$('#historyDetail').addEventListener('click',e=>{if(e.target.id==='historyDetail')e.currentTarget.hidden=true})});
  window.HistoryUI={render};
})();
