(function(){
  const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  let capture=null,messages=[];
  const host=()=>window.JapoLensHost||null;
  const close=()=>{try{host()?.closeOverlay?.()}catch(_error){history.back()}};
  const recapture=()=>{try{host()?.recapture?.()}catch(_error){close()}};
  const parsePayload=()=>{try{return JSON.parse(host()?.getPayload?.()||'{}')}catch{return {}}};
  const endpoint=settings=>(settings?.aiEndpoint||'https://japoteacher-ai.raul-nihongo.workers.dev/evaluate').replace(/\/evaluate$/,'/lens');
  const localDate=()=>{const date=new Date();return [date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-')};
  function japanese(text,readings=[]){const source=String(text||''),items=(readings||[]).map(item=>({term:item.term||item.characters||'',reading:item.reading_hiragana||item.reading||''})).filter(item=>item.term&&item.reading).sort((a,b)=>b.term.length-a.term.length);let html='',index=0;while(index<source.length){const item=items.find(entry=>source.startsWith(entry.term,index));if(item){html+=`<ruby>${esc(item.term)}<rt>${esc(item.reading)}</rt></ruby>`;index+=item.term.length}else{html+=esc(source[index]);index++}}return html}
  const list=items=>(items||[]).filter(Boolean).map(item=>`<li>${esc(item)}</li>`).join('');
  function render(data){const analysis=data.analysis||{},readings=analysis.kanji_vocabulary||[],candidates=analysis.reusable_phrase_candidates||[];capture={...data,capture_id:data.capture_id||crypto.randomUUID()};$('#overlayStatus').hidden=true;const result=$('#overlayResult');result.hidden=false;result.innerHTML=`<header class="result-title"><span class="kicker">${esc(analysis.context_label||'Análisis didáctico')}</span><h2>${esc(analysis.title_es||'Fragmento japonés')}</h2><div class="meta"><span>${esc(data.capture_mode==='vision'?'Visión + OCR':'OCR local')}</span><span>${esc(analysis.jlpt_estimate||'JLPT mixto')}</span></div></header><section class="translation"><span>Traducción natural</span><p>${esc(analysis.translation_es||'')}</p></section><section class="summary"><span>En pocas palabras</span><p>${esc(analysis.overlay_summary_es||(analysis.teacher_explanation||[])[0]||'')}</p></section>${candidates.length?`<p class="candidate-note">${candidates.length} fragmento${candidates.length===1?'':'s'} identificado${candidates.length===1?'':'s'} como material potencial para futuros ejercicios.</p>`:''}<p class="save-note" id="overlaySaveStatus">Guardando el análisis…</p><details open><summary>Texto y lectura</summary><div class="ocr" lang="ja">${japanese(analysis.ocr_text||'',readings)}</div></details><details><summary>Por qué se expresa así</summary><div>${(analysis.teacher_explanation||[]).map(item=>`<p>${esc(item)}</p>`).join('')}<ul>${list(analysis.grammar_points)}</ul></div></details>${readings.length?`<details><summary>Kanji y vocabulario</summary><div>${readings.map(item=>`<article class="vocab-item"><strong lang="ja">${esc(item.term||item.characters||'')}</strong><em>${esc(item.reading_hiragana||'')}</em><p><b>${esc(item.meaning_es||'')}</b> · ${esc(item.note_es||'')}</p></article>`).join('')}</div></details>`:''}${analysis.study_notes?.length?`<details><summary>Notas para aprenderlo</summary><div><ul>${list(analysis.study_notes)}</ul></div></details>`:''}${candidates.length?`<details><summary>Material potencial guardado</summary><div><ul>${list(candidates)}</ul></div></details>`:''}`;$('#overlayChat').hidden=false}
  async function call(body){const [settings,token]=await Promise.all([JapoDB.get('settings','app'),CloudSync.getAccessToken()]);if(!token)throw new Error('Abre JapoTeacher e inicia sesión una vez para usar las explicaciones de la lupa.');const response=await fetch(endpoint(settings?.value||{}),{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,'X-Device-ID':CloudSync.getDeviceId()},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(data.error||`Error HTTP ${response.status}`);return data}
  async function save(data,payload){const settings=(await JapoDB.get('settings','app'))?.value||{},analysis=data.analysis||{},now=new Date().toISOString(),candidates=analysis.reusable_phrase_candidates||[],captureId=data.capture_id||crypto.randomUUID();data.capture_id=captureId;await JapoDB.put('lens_captures',{capture_id:captureId,profile_id:settings.profileId||'local-default',created_at:now,updated_at:now,local_date:localDate(),mode:data.capture_mode,context:payload.context||'',context_detail:payload.context||'',input_text:payload.text||'',ocr_text:analysis.ocr_text||'',title_es:analysis.title_es||'',translation_es:analysis.translation_es||'',jlpt_estimate:analysis.jlpt_estimate||'',overlay_summary_es:analysis.overlay_summary_es||'',analysis_json:JSON.stringify(analysis),reusable_phrase_candidates_json:JSON.stringify(candidates),candidate_count:candidates.length,candidate_status:candidates.length?'pending_editorial_review':'none',candidate_source:'lens_overlay',usage_json:JSON.stringify(data.usage||{}),model:data.model||'',response_id:data.response_id||'',has_image:data.capture_mode==='vision'});await CloudSync.flush()}
  async function analyze(){const payload=parsePayload(),mode=payload.imageDataUrl?'vision':'text';if(!payload.text&&!payload.imageDataUrl)throw new Error('El recorte no contiene texto ni imagen para analizar.');const data=await call({operation:'analyze',mode,context:'overlay',context_detail:String(payload.context||'').slice(0,180),text:String(payload.text||'').slice(0,5000),image_data_url:mode==='vision'?payload.imageDataUrl:''});data.capture_mode=mode;render(data);try{await save(data,payload);$('#overlaySaveStatus').textContent='Análisis y material potencial sincronizados.'}catch(_error){$('#overlaySaveStatus').textContent='La explicación está lista; la sincronización se reintentará al abrir JapoTeacher.'}}
  function renderThread(){const target=$('#overlayThread');target.innerHTML=messages.map(message=>`<div class="message ${message.role}">${esc(message.content)}</div>`).join('');target.scrollTop=target.scrollHeight}
  async function ask(){const button=$('#overlayAsk'),input=$('#overlayQuestion'),question=input.value.trim();if(!question||!capture)return;messages.push({role:'user',content:question});renderThread();input.value='';button.disabled=true;button.textContent='Pensando…';try{const data=await call({operation:'chat',mode:capture.capture_mode,question,analysis:capture.analysis,messages:messages.slice(-8)}),answer=data.answer?.answer_es||'No se pudo preparar una respuesta.';messages.push({role:'assistant',content:answer});await JapoDB.batch(async()=>{await JapoDB.put('lens_messages',{message_id:crypto.randomUUID(),capture_id:capture.capture_id,created_at:new Date().toISOString(),role:'user',content:question});await JapoDB.put('lens_messages',{message_id:crypto.randomUUID(),capture_id:capture.capture_id,created_at:new Date().toISOString(),role:'assistant',content:answer})});await CloudSync.flush()}catch(error){messages.push({role:'assistant',content:error.message||'No se pudo responder.'})}finally{button.disabled=false;button.textContent='Preguntar';renderThread()}}
  async function init(){const preview=new URLSearchParams(location.search).get('preview')==='1'&&['127.0.0.1','localhost'].includes(location.hostname);if(preview){render({capture_mode:'text',analysis:{context_label:'Manga · conversación informal',title_es:'Una invitación entre amigos',ocr_text:'明日、一緒に映画を見に行かない？',translation_es:'¿No quieres ir mañana a ver una película conmigo?',overlay_summary_es:'Es una invitación informal y suave. La forma negativa funciona como propuesta, no como rechazo.',teacher_explanation:['行かない？ usa la forma negativa con entonación interrogativa para invitar sin imponer.','一緒に indica que la actividad se hará en compañía.'],grammar_points:['Vない？: invitación informal frecuente entre personas cercanas.'],kanji_vocabulary:[{term:'明日',reading_hiragana:'あした',meaning_es:'mañana',note_es:'Lectura cotidiana.'},{term:'映画',reading_hiragana:'えいが',meaning_es:'película',note_es:'Sustantivo.'}],study_notes:['En un contexto formal sería más natural 行きませんか。'],reusable_phrase_candidates:['明日、一緒に映画を見に行かない？'],jlpt_estimate:'N4'}});$('#overlaySaveStatus').textContent='Vista previa local';return}try{await JapoDB.open();await CloudSync.initialSync;await analyze()}catch(error){$('#overlayStatus').hidden=true;$('#overlayResult').hidden=false;$('#overlayResult').innerHTML=`<p class="error">${esc(error.message||'No se pudo preparar la explicación.')}</p>`}}
  document.addEventListener('DOMContentLoaded',()=>{$('#closeOverlay').addEventListener('click',close);$('#finishOverlay').addEventListener('click',close);$('#recaptureOverlay').addEventListener('click',recapture);$('#overlayAsk').addEventListener('click',ask);$('#overlayQuestion').addEventListener('keydown',event=>{if(event.key==='Enter'&&(event.ctrlKey||event.metaKey))ask()});init()});
})();
