(function(){
  const $=selector=>document.querySelector(selector);
  let timer;
  function scoreClass(score){return score>=80?'strong':score>=65?'steady':score>=45?'review':'weak'}
  function historyMarkup(attempts,total=attempts.length){const label=total?`Resuelta ${total} vez${total===1?'':'es'}`:'Aún no la has resuelto';const orbs=Array.from({length:5},(_,index)=>{const attempt=attempts[index];if(!attempt)return '<span class="practice-score-orb empty" aria-label="Sin intento previo">—</span>';const score=Math.round(Number(attempt.overall_score)||0),date=new Date(attempt.attempted_at).toLocaleDateString('es-ES',{day:'numeric',month:'short'});return `<span class="practice-score-orb ${scoreClass(score)}" title="${date}: ${score}/100" aria-label="${date}: ${score} sobre 100">${score}</span>`}).join('');return `<section class="practice-history" id="practiceHistory" aria-live="polite"><div><span class="practice-history-label">${label}</span><small>Últimas cinco puntuaciones</small></div><div class="practice-score-orbs" aria-label="Últimas cinco puntuaciones">${orbs}</div></section>`}
  async function render(){const source=$('#sourceText'),meta=$('.practice-meta'),layout=$('#practiceLayout');if(!source||!meta||!layout||layout.hidden)return;const text=source.textContent.trim();if(!text||text==='Selecciona una sesión para comenzar.')return;const exercises=await JapoDB.all('exercises'),exercise=exercises.find(item=>item.source_text===text);if(!exercise)return;const allAttempts=(await JapoDB.all('attempts')).filter(item=>item.exercise_id===exercise.exercise_id&&item.evaluation_status==='valid').sort((left,right)=>String(right.attempted_at).localeCompare(String(left.attempted_at))),attempts=allAttempts.slice(0,5),current=$('#practiceHistory');if(current)current.outerHTML=historyMarkup(attempts,allAttempts.length);else meta.insertAdjacentHTML('afterend',historyMarkup(attempts,allAttempts.length));}
  function schedule(){clearTimeout(timer);timer=setTimeout(()=>render().catch(()=>{}),0)}
  document.addEventListener('DOMContentLoaded',()=>{const source=$('#sourceText'),input=$('#answerInput');if(source)new MutationObserver(schedule).observe(source,{childList:true,characterData:true,subtree:true});input?.addEventListener('focus',schedule);schedule()});
})();
