(function(){
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const directionName=direction=>direction==='ja_es'?'Japonés a español':'Español a japonés';
  const periodLabel=value=>new Date(value).toLocaleDateString('es-ES',{day:'numeric',month:'short',year:'numeric'});
  function period(type,date=new Date()){const end=new Date(date),start=new Date(date);if(type==='weekly'){start.setDate(end.getDate()-6)}else{start.setDate(1);start.setMonth(start.getMonth()-1);end.setDate(0)}start.setHours(0,0,0,0);end.setHours(23,59,59,999);return{start:start.toISOString(),end:end.toISOString()}}
  function localId(report){return `${report.report_type}:${String(report.period_start).slice(0,10)}:${String(report.period_end).slice(0,10)}`}
  async function ensureDraft(type){const {start,end}=period(type),id=`${type}:${start.slice(0,10)}:${end.slice(0,10)}`;if(await JapoDB.get('learning_reports',id))return;const attempts=(await JapoDB.all('attempts')).filter(a=>a.attempted_at>=start&&a.attempted_at<=end);if(!attempts.length)return;const metrics={};for(const direction of ['ja_es','es_ja']){const list=attempts.filter(a=>a.direction===direction);metrics[direction]={count:list.length,average:list.length?Math.round(list.reduce((n,a)=>n+(a.overall_score||0),0)/list.length):0}}await JapoDB.put('learning_reports',{report_id:id,report_type:type,period_start:start,period_end:end,created_at:new Date().toISOString(),status:'awaiting_ai',attempt_count:attempts.length,direction_metrics:metrics,summary:'',strengths:[],priority_structures:[],priority_vocabulary:[],action_plan:[],cumulative_progress:{},previous_report_ids:[]})}
  async function ensureDue(){const d=new Date();if(d.getDay()===0)await ensureDraft('weekly');if(d.getDate()===1)await ensureDraft('monthly')}
  async function request(path,body={}){const token=await window.CloudSync?.getAccessToken();if(!token)throw new Error('Inicia sesión para generar y conservar informes.');const settings=(await JapoDB.get('settings','app'))?.value||{},endpoint=(settings.aiEndpoint||'').replace(/\/evaluate$/,path);if(!endpoint)throw new Error('Falta la URL del Worker.');const response=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','X-Device-ID':window.CloudSync?.getDeviceId?.()||''},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo generar el informe.');return data}
  async function sync(){try{const {reports=[]}=await request('/reports/list');if(reports.length)await JapoDB.bulkPut('learning_reports',reports.map(report=>({...report,report_id:localId(report)})));}catch(error){if(!/Inicia sesión/.test(error.message))console.warn(error)}}
  function list(values,empty){return values?.length?`<ul>${values.map(value=>`<li>${esc(typeof value==='string'?value:value.title||'')}</li>`).join('')}</ul>`:`<p class="empty">${empty}</p>`}
  function metric(value){return Math.max(0,Math.min(100,Math.round(Number(value)||0)))}
  function profileValues(item){return [['Comprensión',metric(item.comprehensibility||item.average)],['Precisión',metric(item.objective||item.average)],['Gramática',metric(item.grammar||item.average)],['Léxico',metric(item.vocabulary||item.average)],['Naturalidad',metric(item.naturalness||item.average)]]}
  function directionPanel(direction,item){const score=metric(item?.average),values=profileValues(item||{});return `<section class="report-direction-panel ${direction}"><div class="report-direction-top"><div><p>${direction==='ja_es'?'Comprender japonés':'Producir japonés'}</p><h5>${directionName(direction)}</h5></div><strong>${score}<small>/100</small></strong></div><span class="report-attempts">${item?.count||0} respuestas evaluadas</span><div class="report-skill-rows">${values.map(([label,value])=>`<div><span>${label}</span><i><b style="width:${value}%"></b></i><em>${value}</em></div>`).join('')}</div></section>`}
  function reportError(error){const message=String(error?.message||'No se pudo generar el informe.').replace(/^Supabase reports:\s*/,'');return `No se pudo generar el informe: ${message}`}
  function readyBody(report){const assessment=report.teacher_assessment||report.cumulative_progress?.teacher_assessment||{},diagnosis=assessment.narrative||report.summary||'Aún no hay una valoración narrativa para este periodo.',headline=assessment.headline||'Lectura del periodo';const actions=report.action_plan?.length?`<div class="report-actions-list">${report.action_plan.map((action,index)=>`<article><span>${String(index+1).padStart(2,'0')}</span><div><strong>${esc(action.title)}</strong><p>${esc(action.reason)}</p><b>${esc(action.target)}</b></div></article>`).join('')}</div>`:'<p class="empty">No hay acciones adicionales para este periodo.</p>';return `<section class="report-teacher-note"><p>Valoración docente</p><h5>${esc(headline)}</h5><p>${esc(diagnosis)}</p></section><section class="report-profile"><div><p class="report-section-label">Perfil de competencia</p><h5>Radiografía de las dos direcciones</h5><p>Las barras se calculan a partir de las respuestas evaluadas durante el periodo.</p></div><canvas class="report-profile-canvas" width="320" height="210" data-profile='${esc(JSON.stringify(report.direction_metrics||{}))}' aria-label="Perfil de competencia"></canvas></section><div class="report-insights"><section><p>Fortalezas</p>${list(report.strengths,'Todavía no hay fortalezas consolidadas.')}</section><section><p>Intervención gramatical</p>${list(report.priority_structures,'Sin prioridad gramatical nueva.')}</section><section><p>Vocabulario y precisión</p>${list(report.priority_vocabulary,'Sin prioridad léxica nueva.')}</section></div><section class="report-plan"><div><p class="report-section-label">Itinerario recomendado</p><h5>Próximas sesiones</h5><p>Un plan breve, observable y medible para el siguiente periodo.</p></div>${actions}</section><section class="report-trend"><span>Tendencia acumulada</span><p>${esc(report.cumulative_progress?.trend||'El próximo informe podrá comparar esta línea base con tu evolución.')}</p></section>`}
  function reportCard(report,filter){const directions=filter==='all'?['ja_es','es_ja']:[filter],label=report.report_type==='weekly'?'Informe semanal':'Informe mensual',average=directions.length?Math.round(directions.reduce((sum,direction)=>sum+(report.direction_metrics?.[direction]?.average||0),0)/directions.length):0;return `<article class="learning-report-card ${report.status}"><header class="report-document-head"><div><p>${label}</p><h4>${periodLabel(report.period_start)} - ${periodLabel(report.period_end)}</h4></div><div><strong>${average}<small>/100</small></strong><span class="report-status ${report.status}">${report.status==='ready'?'Preparado':report.status==='failed'?'No disponible':report.status==='generating'?'Elaborando':'En espera'}</span></div></header><div class="report-direction-grid">${directions.map(direction=>directionPanel(direction,report.direction_metrics?.[direction])).join('')}</div>${report.status==='ready'?readyBody(report):`<p class="empty report-pending">${report.status==='failed'?esc(report.error_message||'No se pudo generar el informe.'):'Estamos reuniendo la evidencia necesaria para elaborar una valoración útil.'}</p>`}</article>`}
  function drawProfiles(root){root.querySelectorAll('.report-profile-canvas').forEach(canvas=>{let data={};try{data=JSON.parse(canvas.dataset.profile||'{}')}catch{}const ctx=canvas.getContext('2d'),width=canvas.width,height=canvas.height,centerX=width/2,centerY=height/2+8,radius=72,labels=['Comprensión','Precisión','Gramática','Léxico','Naturalidad'],values=labels.map((_,index)=>Math.round(((profileValues(data.ja_es||{})[index][1])+(profileValues(data.es_ja||{})[index][1]))/2));ctx.clearRect(0,0,width,height);ctx.font='11px system-ui';ctx.textAlign='center';for(let ring=1;ring<=4;ring++){ctx.beginPath();labels.forEach((_,index)=>{const angle=-Math.PI/2+index*Math.PI*2/labels.length,point=radius*ring/4,x=centerX+Math.cos(angle)*point,y=centerY+Math.sin(angle)*point;index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.strokeStyle='#d9dce0';ctx.lineWidth=1;ctx.stroke()}labels.forEach((label,index)=>{const angle=-Math.PI/2+index*Math.PI*2/labels.length,x=centerX+Math.cos(angle)*(radius+25),y=centerY+Math.sin(angle)*(radius+25);ctx.fillStyle='#5d6269';ctx.fillText(label,x,y+4)});ctx.beginPath();values.forEach((value,index)=>{const angle=-Math.PI/2+index*Math.PI*2/labels.length,point=radius*value/100,x=centerX+Math.cos(angle)*point,y=centerY+Math.sin(angle)*point;index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle='rgba(181,43,33,.18)';ctx.fill();ctx.strokeStyle='#b52b21';ctx.lineWidth=2;ctx.stroke()})}
  async function render(filter='all'){const root=document.querySelector('#learningReports');if(!root)return;const reports=(await JapoDB.all('learning_reports')).sort((a,b)=>String(b.period_end).localeCompare(String(a.period_end)));root.innerHTML=reports.length?reports.map(report=>reportCard(report,filter)).join(''):'<p class="empty">Genera un informe cuando tengas práctica suficiente; se guardará en tu cuenta.</p>';drawProfiles(root)}
  async function generate(type){const button=document.querySelector('#generateReportButton');if(button){button.disabled=true;button.textContent='Elaborando informe...'}try{const {report}=await request('/reports/generate',{report_type:type,ad_hoc:type==='weekly',force:true});await JapoDB.put('learning_reports',{...report,report_id:localId(report)});await render(document.querySelector('#progressDirection')?.value||'all');window.UI.toast(report.attempt_count<3?'Informe guardado: falta más evidencia para conclusiones fiables.':'Informe pedagógico preparado');}catch(error){window.UI.toast(reportError(error))}finally{if(button){button.disabled=false;button.textContent='Generar informe'}}}
  function print(){window.print()}
  if(document.addEventListener)document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#generateReportButton')?.addEventListener('click',event=>generate(event.currentTarget.dataset.reportType));document.querySelector('#reportType')?.addEventListener('change',event=>{document.querySelector('#generateReportButton').dataset.reportType=event.target.value});document.querySelector('#printReportButton')?.addEventListener('click',print)});
  window.LearningReports={ensureDue,render,period,sync,generate};
})();
