(function(){
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function period(type,date=new Date()){const end=new Date(date),start=new Date(date);if(type==='weekly'){start.setDate(end.getDate()-6)}else{start.setDate(1);start.setMonth(start.getMonth()-1);end.setDate(0)}start.setHours(0,0,0,0);end.setHours(23,59,59,999);return{start:start.toISOString(),end:end.toISOString()}}
  function localId(report){return `${report.report_type}:${String(report.period_start).slice(0,10)}:${String(report.period_end).slice(0,10)}`}
  async function ensureDraft(type){const {start,end}=period(type),id=`${type}:${start.slice(0,10)}:${end.slice(0,10)}`;if(await JapoDB.get('learning_reports',id))return;const attempts=(await JapoDB.all('attempts')).filter(a=>a.attempted_at>=start&&a.attempted_at<=end);if(!attempts.length)return;const metrics={};for(const direction of ['ja_es','es_ja']){const list=attempts.filter(a=>a.direction===direction);metrics[direction]={count:list.length,average:list.length?Math.round(list.reduce((n,a)=>n+(a.overall_score||0),0)/list.length):0}}await JapoDB.put('learning_reports',{report_id:id,report_type:type,period_start:start,period_end:end,created_at:new Date().toISOString(),status:'awaiting_ai',attempt_count:attempts.length,direction_metrics:metrics,summary:'',strengths:[],priority_structures:[],priority_vocabulary:[],action_plan:[],cumulative_progress:{},previous_report_ids:[]})}
  async function ensureDue(){const d=new Date();if(d.getDay()===0)await ensureDraft('weekly');if(d.getDate()===1)await ensureDraft('monthly')}
  async function request(path,body={}){const token=await window.CloudSync?.getAccessToken();if(!token)throw new Error('Inicia sesión para generar y conservar informes.');const settings=(await JapoDB.get('settings','app'))?.value||{},endpoint=(settings.aiEndpoint||'').replace(/\/evaluate$/,path);if(!endpoint)throw new Error('Falta la URL del Worker.');const response=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','X-Device-ID':window.CloudSync?.getDeviceId?.()||''},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo generar el informe.');return data}
  async function sync(){try{const {reports=[]}=await request('/reports/list');if(reports.length)await JapoDB.bulkPut('learning_reports',reports.map(report=>({...report,report_id:localId(report)})));}catch(error){if(!/Inicia sesión/.test(error.message))console.warn(error)}}
  function list(values,empty){return values?.length?`<ul>${values.map(value=>`<li>${esc(typeof value==='string'?value:value.title||'')}</li>`).join('')}</ul>`:`<p class="empty">${empty}</p>`}
  function readyBody(report){const actions=report.action_plan?.length?`<div class="report-actions-list">${report.action_plan.map(action=>`<article><strong>${esc(action.title)}</strong><p>${esc(action.reason)}</p><span>${esc(action.target)}</span></article>`).join('')}</div>`:'<p class="empty">No hay acciones adicionales para este periodo.</p>';return `<p class="report-summary">${esc(report.summary)}</p><div class="report-insights"><section><h5>Fortalezas</h5>${list(report.strengths,'Aún no hay fortalezas consolidadas.')}</section><section><h5>Prioridad gramatical</h5>${list(report.priority_structures,'Sin prioridad gramatical nueva.')}</section><section><h5>Vocabulario</h5>${list(report.priority_vocabulary,'Sin prioridad de vocabulario nueva.')}</section></div><section class="report-plan"><div><p class="section-kicker">Próximo paso</p><h5>Plan de práctica</h5></div>${actions}</section><p class="report-trend">${esc(report.cumulative_progress?.trend||'Sin comparación acumulada todavía.')}</p>`}
  async function render(filter='all'){const root=document.querySelector('#learningReports');if(!root)return;const reports=(await JapoDB.all('learning_reports')).sort((a,b)=>String(b.period_end).localeCompare(String(a.period_end))),directions=filter==='all'?['ja_es','es_ja']:[filter];root.innerHTML=reports.length?reports.map(report=>`<article class="learning-report-card ${report.status}"><header><div><span>${report.report_type==='weekly'?'Informe semanal':'Informe mensual'}</span><h4>${new Date(report.period_start).toLocaleDateString('es-ES')} – ${new Date(report.period_end).toLocaleDateString('es-ES')}</h4></div><b class="report-status ${report.status}">${report.status==='ready'?'Listo':report.status==='failed'?'No disponible':report.status==='generating'?'Generando':'Pendiente'}</b></header><div class="report-direction-grid">${directions.map(direction=>`<div><strong>${report.direction_metrics?.[direction]?.average||0}%</strong><span>${direction==='ja_es'?'JP → ES':'ES → JP'} · ${report.direction_metrics?.[direction]?.count||0} intentos</span></div>`).join('')}</div>${report.status==='ready'?readyBody(report):`<p class="empty">${report.status==='failed'?esc(report.error_message||'No se pudo generar el informe.'):'Reúne evidencia y genera un análisis cuando quieras.'}</p>`}</article>`).join(''):'<p class="empty">Genera un informe cuando tengas práctica suficiente; se guardará en tu cuenta.</p>'}
  function reportError(error){const message=error?.message||'No se pudo generar el informe.';return /required privileges|permission denied|42501/i.test(message)?'Faltan permisos del Worker sobre los datos de aprendizaje. Ejecuta de nuevo la migración 004 actualizada.':message}
  async function generate(type){const button=document.querySelector('#generateReportButton');if(button){button.disabled=true;button.textContent='Generando informe…'}try{const {report}=await request('/reports/generate',{report_type:type,ad_hoc:type==='weekly'});await JapoDB.put('learning_reports',{...report,report_id:localId(report)});await render(document.querySelector('#progressDirection')?.value||'all');window.UI.toast(report.attempt_count<3?'Informe guardado: falta más evidencia para conclusiones fiables.':'Informe generado');}catch(error){window.UI.toast(reportError(error))}finally{if(button){button.disabled=false;button.textContent='Generar informe'}}}
  if(document.addEventListener)document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#generateReportButton')?.addEventListener('click',event=>generate(event.currentTarget.dataset.reportType));document.querySelector('#reportType')?.addEventListener('change',event=>{document.querySelector('#generateReportButton').dataset.reportType=event.target.value})});
  window.LearningReports={ensureDue,render,period,sync,generate};
})();
