(function(){
  const localDate=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
  function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
  function seededSort(items,seed){return [...items].sort((a,b)=>hash(seed+a.exercise_id)-hash(seed+b.exercise_id));}
  function similarity(a,b){const at=new Set([...(a.grammar_tags||[]),...(a.vocabulary_tags||[])]),bt=new Set([...(b.grammar_tags||[]),...(b.vocabulary_tags||[])]);let n=0;at.forEach(x=>{if(bt.has(x))n++});return n/Math.max(1,Math.min(at.size,bt.size));}
  function choose(exercises,progress,attempts,count,settings,direction,date,roadmap){const pMap=new Map(progress.map(p=>[p.exercise_id,p]));const now=Date.now();const eligible=exercises.filter(e=>e.direction===direction&&e.active!==false&&(settings.levels.includes(e.jlpt_level)||(e.topic_tags||[]).some(topic=>roadmap.find(x=>x.topic===topic)?.target===e.jlpt_level))).filter(e=>{const p=pMap.get(e.exercise_id);return !p||!p.cooldown_until||new Date(p.cooldown_until).getTime()<=now||new Date(p.next_review_at).getTime()<=now;});const score=e=>{const p=pMap.get(e.exercise_id),srs=p?(new Date(p.next_review_at).getTime()<=now?100:0)+(100-(p.average_score||0)):55;return srs+TopicProgression.bonus(e,roadmap)};const ranked=seededSort(eligible,date+direction).sort((a,b)=>score(b)-score(a));const selected=[];for(const e of ranked){if(selected.some(x=>similarity(x,e)>.8))continue;selected.push(e);if(selected.length===count)break}if(selected.length<count){for(const e of ranked){if(!selected.includes(e))selected.push(e);if(selected.length===count)break}}return selected.map(e=>e.exercise_id)}
  async function getOrCreate(profileId,settings){const date=localDate(),id=`${profileId}::${date}`;const existing=await JapoDB.get('daily_sessions',id);if(existing&&(existing.planned_ja_es>0||existing.planned_es_ja>0))return existing;const [exercises,progress,attempts]=await Promise.all([JapoDB.all('exercises'),JapoDB.all('exercise_progress'),JapoDB.all('attempts')]),roadmap=TopicProgression.analyze(exercises,attempts);const ja=choose(exercises,progress,attempts,settings.dailyJaEs,settings,'ja_es',date,roadmap),es=choose(exercises,progress,attempts,settings.dailyEsJa,settings,'es_ja',date,roadmap);const now=new Date().toISOString();const session={session_id:id,profile_id:profileId,local_date:date,created_at:existing?.created_at||now,started_at:existing?.started_at||null,completed_at:null,planned_ja_es:ja.length,planned_es_ja:es.length,exercise_ids_ja_es_json:JSON.stringify(ja),exercise_ids_es_ja_json:JSON.stringify(es),completed_exercise_ids_json:existing?.completed_exercise_ids_json||'[]',status:'planned',selection_reason_json:JSON.stringify({strategy:'topic_adaptive_srs_v2',targets:Object.fromEntries(roadmap.map(x=>[x.topic,x.target])),repaired_empty_plan:Boolean(existing)}),settings_snapshot_json:JSON.stringify(settings),drafts_json:existing?.drafts_json||'{}'};await JapoDB.put('daily_sessions',session);return session;}
  window.SessionPlanner={localDate,getOrCreate};
})();
