(function(){
  const localDate=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
  function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
  function seededSort(items,seed){return [...items].sort((a,b)=>hash(seed+a.exercise_id)-hash(seed+b.exercise_id))}
  function similarity(a,b){const at=new Set([...(a.grammar_tags||[]),...(a.vocabulary_tags||[])]),bt=new Set([...(b.grammar_tags||[]),...(b.vocabulary_tags||[])]);let n=0;at.forEach(x=>{if(bt.has(x))n++});return n/Math.max(1,Math.min(at.size,bt.size))}
  function choose(exercises,progress,attempts,count,settings,direction,date,roadmap){
    const pMap=new Map(progress.map(p=>[p.exercise_id,p])),eMap=new Map(exercises.map(e=>[e.exercise_id,e])),now=Date.now(),signals=new Map();
    const recent=attempts.filter(a=>a.direction===direction&&a.evaluation_status==='valid').sort((a,b)=>String(a.attempted_at).localeCompare(String(b.attempted_at))).slice(-20);
    recent.forEach((attempt,index)=>{const exercise=eMap.get(attempt.exercise_id),score=attempt.overall_score||0,recency=(index+1)/recent.length,delta=score<75?(75-score)*.9*recency:score>=85?-(score-85)*.35*recency:0;if(!exercise||!delta)return;for(const tag of [...(exercise.topic_tags||[]),...(exercise.grammar_tags||[]),...(exercise.vocabulary_tags||[])])signals.set(tag,(signals.get(tag)||0)+delta)});
    const adaptiveBonus=exercise=>Math.max(-45,Math.min(130,[...(exercise.topic_tags||[]),...(exercise.grammar_tags||[]),...(exercise.vocabulary_tags||[])].reduce((sum,tag)=>sum+(signals.get(tag)||0),0)));
    const eligible=exercises.filter(e=>e.direction===direction&&e.active!==false&&(settings.levels.includes(e.jlpt_level)||(e.topic_tags||[]).some(topic=>roadmap.find(x=>x.topic===topic)?.target===e.jlpt_level))).filter(e=>{const p=pMap.get(e.exercise_id);return !p||!p.cooldown_until||new Date(p.cooldown_until).getTime()<=now||new Date(p.next_review_at).getTime()<=now});
    const recentAverage=recent.length?recent.reduce((sum,a)=>sum+(a.overall_score||0),0)/recent.length:75;
    const targetDifficulty=recentAverage<65?35:recentAverage>88?70:55;
    const activeLevelIndexes=settings.levels.map(level=>Difficulty.levelIndex({jlpt_level:level})).filter(Number.isFinite),recentLevelIndexes=recent.map(attempt=>Difficulty.levelIndex(eMap.get(attempt.exercise_id))).filter(index=>index<5),preferredLevel=recentLevelIndexes.length?Math.min(...recentLevelIndexes):Math.min(...activeLevelIndexes);
    const difficultyBonus=e=>20-Math.min(40,Math.abs(Difficulty.score(e)-targetDifficulty)*.8)-Math.max(0,Difficulty.levelIndex(e)-preferredLevel)*45;
    const score=e=>{const p=pMap.get(e.exercise_id),srs=p?(new Date(p.next_review_at).getTime()<=now?100:0)+(100-(p.average_score||0)):55;return srs+TopicProgression.bonus(e,roadmap)+adaptiveBonus(e)+difficultyBonus(e)};
    const ranked=seededSort(eligible,date+direction).sort((a,b)=>score(b)-score(a)),selected=[];
    for(const e of ranked){if(selected.some(x=>similarity(x,e)>.8))continue;selected.push(e);if(selected.length===count)break}
    if(selected.length<count)for(const e of ranked){if(!selected.includes(e))selected.push(e);if(selected.length===count)break}
    return selected.map(e=>e.exercise_id)
  }
  async function getOrCreate(profileId,settings,date=localDate()){
    const id=`${profileId}::${date}`;
    const [existing,exercises,progress,attempts]=await Promise.all([JapoDB.get('daily_sessions',id),JapoDB.all('exercises'),JapoDB.all('exercise_progress'),JapoDB.all('attempts')]);
    const roadmaps={ja_es:TopicProgression.analyze(exercises,attempts,'ja_es'),es_ja:TopicProgression.analyze(exercises,attempts,'es_ja')},completed=new Set(JSON.parse(existing?.completed_exercise_ids_json||'[]')),activeIds=new Set(exercises.filter(e=>e.active!==false).map(e=>e.exercise_id));
    const repair=(field,direction,target)=>{const kept=JSON.parse(existing?.[field]||'[]').filter(exerciseId=>activeIds.has(exerciseId)||completed.has(exerciseId)),candidates=choose(exercises,progress,attempts,target,settings,direction,`${date}::repair`,roadmaps[direction]);for(const exerciseId of candidates){if(kept.length>=target)break;if(!kept.includes(exerciseId))kept.push(exerciseId)}return kept};
    const ja=existing?repair('exercise_ids_ja_es_json','ja_es',settings.dailyJaEs):choose(exercises,progress,attempts,settings.dailyJaEs,settings,'ja_es',date,roadmaps.ja_es),es=existing?repair('exercise_ids_es_ja_json','es_ja',settings.dailyEsJa):choose(exercises,progress,attempts,settings.dailyEsJa,settings,'es_ja',date,roadmaps.es_ja);
    const changed=existing&&(existing.exercise_ids_ja_es_json!==JSON.stringify(ja)||existing.exercise_ids_es_ja_json!==JSON.stringify(es));if(existing&&!changed&&(existing.planned_ja_es>0||existing.planned_es_ja>0))return existing;
    const now=new Date().toISOString(),session={...existing,session_id:id,profile_id:profileId,local_date:date,created_at:existing?.created_at||now,started_at:existing?.started_at||null,completed_at:existing?.completed_at||null,planned_ja_es:ja.length,planned_es_ja:es.length,exercise_ids_ja_es_json:JSON.stringify(ja),exercise_ids_es_ja_json:JSON.stringify(es),completed_exercise_ids_json:existing?.completed_exercise_ids_json||'[]',status:existing?.status||'planned',selection_reason_json:JSON.stringify({strategy:'topic_adaptive_srs_v4',targets:{ja_es:Object.fromEntries(roadmaps.ja_es.map(x=>[x.topic,x.target])),es_ja:Object.fromEntries(roadmaps.es_ja.map(x=>[x.topic,x.target]))},repaired_archived_plan:Boolean(changed)}),settings_snapshot_json:JSON.stringify(settings),drafts_json:existing?.drafts_json||'{}'};await JapoDB.put('daily_sessions',session);return session;
  }
  async function createExtra(profileId,settings){const date=localDate(),seed=`${date}::extra::${Date.now()}`,[exercises,progress,attempts]=await Promise.all([JapoDB.all('exercises'),JapoDB.all('exercise_progress'),JapoDB.all('attempts')]),roadmaps={ja_es:TopicProgression.analyze(exercises,attempts,'ja_es'),es_ja:TopicProgression.analyze(exercises,attempts,'es_ja')},ja=choose(exercises,progress,attempts,settings.dailyJaEs,settings,'ja_es',seed,roadmaps.ja_es),es=choose(exercises,progress,attempts,settings.dailyEsJa,settings,'es_ja',seed,roadmaps.es_ja),now=new Date().toISOString(),session={session_id:`${profileId}::${seed}`,profile_id:profileId,local_date:date,created_at:now,started_at:null,completed_at:null,planned_ja_es:ja.length,planned_es_ja:es.length,exercise_ids_ja_es_json:JSON.stringify(ja),exercise_ids_es_ja_json:JSON.stringify(es),completed_exercise_ids_json:'[]',status:'planned',selection_reason_json:JSON.stringify({strategy:'extra_topic_adaptive_srs_v2',targets:{ja_es:Object.fromEntries(roadmaps.ja_es.map(x=>[x.topic,x.target])),es_ja:Object.fromEntries(roadmaps.es_ja.map(x=>[x.topic,x.target]))}}),settings_snapshot_json:JSON.stringify(settings),drafts_json:'{}',session_kind:'extra'};await JapoDB.put('daily_sessions',session);return session}
  window.SessionPlanner={localDate,getOrCreate,createExtra};
})();
