(function(){
  const localDate=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
  const hash=s=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
  const seededSort=(items,seed)=>[...items].sort((a,b)=>hash(seed+a.exercise_id)-hash(seed+b.exercise_id));
  const similarity=(a,b)=>{const at=new Set([...(a.grammar_tags||[]),...(a.vocabulary_tags||[])]),bt=new Set([...(b.grammar_tags||[]),...(b.vocabulary_tags||[])]);let n=0;at.forEach(x=>{if(bt.has(x))n++});return n/Math.max(1,Math.min(at.size,bt.size))};
  const validAttempts=attempts=>attempts.filter(attempt=>attempt.evaluation_status==='valid'&&Number.isFinite(Number(attempt.overall_score)));

  // The 0-100 difficulty scale advances independently in every JLPT and direction.
  function difficultyRoadmap(exercises,attempts,direction){
    const latestByExercise=new Map();
    for(const attempt of validAttempts(attempts.filter(item=>item.direction===direction)).sort((a,b)=>String(a.attempted_at).localeCompare(String(b.attempted_at))))latestByExercise.set(attempt.exercise_id,attempt);
    const levels=[...new Set(exercises.filter(exercise=>exercise.active!==false&&exercise.direction===direction).map(exercise=>exercise.jlpt_level))];
    return Object.fromEntries(levels.map(level=>{
      const states=Difficulty.bands.map((band,index)=>{
        const items=exercises.filter(exercise=>exercise.active!==false&&exercise.direction===direction&&exercise.jlpt_level===level&&Difficulty.bandFor(exercise)===index),results=items.map(exercise=>latestByExercise.get(exercise.exercise_id)).filter(Boolean),required=Math.min(4,items.length),average=results.length?Math.round(results.reduce((sum,item)=>sum+Number(item.overall_score),0)/results.length):0,acceptable=results.length?results.filter(item=>item.is_acceptable).length/results.length:0;
        return {index,count:items.length,seen:results.length,required,average,acceptable,mastered:items.length===0||(results.length>=required&&average>=82&&acceptable>=.75)};
      });
      let unlockedBand=0;
      for(let index=0;index<states.length-1;index++){if(!states[index].mastered)break;unlockedBand=index+1}
      return [level,{unlockedBand,bands:states}];
    }));
  }

  function choose(exercises,progress,attempts,count,settings,direction,date,roadmap){
    const pMap=new Map(progress.map(item=>[item.exercise_id,item])),eMap=new Map(exercises.map(item=>[item.exercise_id,item])),now=Date.now(),signals=new Map(),valid=validAttempts(attempts),attemptedIds=new Set(valid.map(item=>item.exercise_id)),gates=difficultyRoadmap(exercises,attempts,direction);
    const recent=valid.filter(item=>item.direction===direction).sort((a,b)=>String(a.attempted_at).localeCompare(String(b.attempted_at))).slice(-20);
    recent.forEach((attempt,index)=>{const exercise=eMap.get(attempt.exercise_id),score=attempt.overall_score||0,recency=(index+1)/recent.length,delta=score<75?(75-score)*.9*recency:score>=85?-(score-85)*.35*recency:0;if(!exercise||!delta)return;for(const tag of [...(exercise.topic_tags||[]),...(exercise.grammar_tags||[]),...(exercise.vocabulary_tags||[])])signals.set(tag,(signals.get(tag)||0)+delta)});
    const adaptiveBonus=exercise=>Math.max(-45,Math.min(130,[...(exercise.topic_tags||[]),...(exercise.grammar_tags||[]),...(exercise.vocabulary_tags||[])].reduce((sum,tag)=>sum+(signals.get(tag)||0),0)));
    const isNewExercise=exercise=>!attemptedIds.has(exercise.exercise_id),isUnlocked=exercise=>Difficulty.bandFor(exercise)<=((gates[exercise.jlpt_level]?.unlockedBand)??0);
    const eligible=exercises.filter(exercise=>exercise.direction===direction&&exercise.active!==false&&(settings.levels.includes(exercise.jlpt_level)||(exercise.topic_tags||[]).some(topic=>roadmap.find(item=>item.topic===topic)?.target===exercise.jlpt_level))).filter(exercise=>{const progressItem=pMap.get(exercise.exercise_id),reviewDue=!progressItem||!progressItem.cooldown_until||new Date(progressItem.cooldown_until).getTime()<=now||new Date(progressItem.next_review_at).getTime()<=now;return reviewDue&&(!isNewExercise(exercise)||isUnlocked(exercise))});
    const recentAverage=recent.length?recent.reduce((sum,item)=>sum+(item.overall_score||0),0)/recent.length:75,targetDifficulty=recentAverage<65?35:recentAverage>88?70:55,activeLevelIndexes=settings.levels.map(level=>Difficulty.levelIndex({jlpt_level:level})).filter(Number.isFinite),recentLevelIndexes=recent.map(attempt=>Difficulty.levelIndex(eMap.get(attempt.exercise_id))).filter(index=>index<5),preferredLevel=recentLevelIndexes.length?Math.min(...recentLevelIndexes):Math.min(...activeLevelIndexes);
    const difficultyBonus=exercise=>{const band=Difficulty.bandFor(exercise),unlocked=(gates[exercise.jlpt_level]?.unlockedBand)??0,bandFocus=band===unlocked?30:band<unlocked?8:-80;return bandFocus+20-Math.min(40,Math.abs(Difficulty.score(exercise)-targetDifficulty)*.8)-Math.max(0,Difficulty.levelIndex(exercise)-preferredLevel)*45};
    const score=exercise=>{const progressItem=pMap.get(exercise.exercise_id),srs=progressItem?(new Date(progressItem.next_review_at).getTime()<=now?100:0)+(100-(progressItem.average_score||0)):55;return srs+TopicProgression.bonus(exercise,roadmap)+adaptiveBonus(exercise)+difficultyBonus(exercise)};
    const ranked=seededSort(eligible,date+direction).sort((a,b)=>score(b)-score(a)),selected=[];
    for(const exercise of ranked){if(selected.some(item=>similarity(item,exercise)>.8))continue;selected.push(exercise);if(selected.length===count)break}
    if(selected.length<count)for(const exercise of ranked){if(!selected.includes(exercise))selected.push(exercise);if(selected.length===count)break}
    return selected.map(exercise=>exercise.exercise_id);
  }

  async function getOrCreate(profileId,settings,date=localDate()){
    const id=`${profileId}::${date}`,[existing,exercises,progress,attempts]=await Promise.all([JapoDB.get('daily_sessions',id),JapoDB.all('exercises'),JapoDB.all('exercise_progress'),JapoDB.all('attempts')]),roadmaps={ja_es:TopicProgression.analyze(exercises,attempts,'ja_es'),es_ja:TopicProgression.analyze(exercises,attempts,'es_ja')},completed=new Set(JSON.parse(existing?.completed_exercise_ids_json||'[]')),activeIds=new Set(exercises.filter(exercise=>exercise.active!==false).map(exercise=>exercise.exercise_id)),exerciseById=new Map(exercises.map(exercise=>[exercise.exercise_id,exercise])),practicedIds=new Set(validAttempts(attempts).map(attempt=>attempt.exercise_id)),difficultyGates={ja_es:difficultyRoadmap(exercises,attempts,'ja_es'),es_ja:difficultyRoadmap(exercises,attempts,'es_ja')};
    const repair=(field,direction,target)=>{const kept=JSON.parse(existing?.[field]||'[]').filter(exerciseId=>{const exercise=exerciseById.get(exerciseId);return completed.has(exerciseId)||activeIds.has(exerciseId)&&(practicedIds.has(exerciseId)||Difficulty.bandFor(exercise)<=((difficultyGates[direction][exercise?.jlpt_level]?.unlockedBand)??0))}),candidates=choose(exercises,progress,attempts,target,settings,direction,`${date}::repair`,roadmaps[direction]);for(const exerciseId of candidates){if(kept.length>=target)break;if(!kept.includes(exerciseId))kept.push(exerciseId)}return kept};
    const ja=existing?repair('exercise_ids_ja_es_json','ja_es',settings.dailyJaEs):choose(exercises,progress,attempts,settings.dailyJaEs,settings,'ja_es',date,roadmaps.ja_es);
    const es=existing?repair('exercise_ids_es_ja_json','es_ja',settings.dailyEsJa):choose(exercises,progress,attempts,settings.dailyEsJa,settings,'es_ja',date,roadmaps.es_ja);
    const changed=existing&&(existing.exercise_ids_ja_es_json!==JSON.stringify(ja)||existing.exercise_ids_es_ja_json!==JSON.stringify(es));
    if(existing&&!changed&&(existing.planned_ja_es>0||existing.planned_es_ja>0))return existing;
    const now=new Date().toISOString(),session={...existing,session_id:id,profile_id:profileId,local_date:date,created_at:existing?.created_at||now,started_at:existing?.started_at||null,completed_at:existing?.completed_at||null,planned_ja_es:ja.length,planned_es_ja:es.length,exercise_ids_ja_es_json:JSON.stringify(ja),exercise_ids_es_ja_json:JSON.stringify(es),completed_exercise_ids_json:existing?.completed_exercise_ids_json||'[]',status:existing?.status||'planned',selection_reason_json:JSON.stringify({strategy:'topic_adaptive_srs_difficulty_gates_v5',targets:{ja_es:Object.fromEntries(roadmaps.ja_es.map(item=>[item.topic,item.target])),es_ja:Object.fromEntries(roadmaps.es_ja.map(item=>[item.topic,item.target]))},difficulty_gates:difficultyGates,repaired_archived_plan:Boolean(changed)}),settings_snapshot_json:JSON.stringify(settings),drafts_json:existing?.drafts_json||'{}'};await JapoDB.put('daily_sessions',session);return session;
  }
  async function createExtra(profileId,settings){const date=localDate(),id=`${profileId}::${date}`,seed=`${date}::extra::${Date.now()}`,[existing,exercises,progress,attempts]=await Promise.all([JapoDB.get('daily_sessions',id),JapoDB.all('exercises'),JapoDB.all('exercise_progress'),JapoDB.all('attempts')]),base=existing||await getOrCreate(profileId,settings,date),roadmaps={ja_es:TopicProgression.analyze(exercises,attempts,'ja_es'),es_ja:TopicProgression.analyze(exercises,attempts,'es_ja')},completed=new Set(JSON.parse(base.completed_exercise_ids_json||'[]')),append=(field,direction,count)=>{const current=JSON.parse(base[field]||'[]'),planned=new Set([...current,...completed]),candidates=choose(exercises,progress,attempts,Math.max(count*4,settings[direction==='ja_es'?'dailyJaEs':'dailyEsJa']||count),settings,direction,`${seed}:${direction}`,roadmaps[direction]).filter(exerciseId=>!planned.has(exerciseId));return [...current,...candidates.slice(0,count)]},ja=append('exercise_ids_ja_es_json','ja_es',1),es=append('exercise_ids_es_ja_json','es_ja',1),history=JSON.parse(base.extra_study_history_json||'[]');history.push({at:new Date().toISOString(),added_ja_es:ja.length-JSON.parse(base.exercise_ids_ja_es_json||'[]').length,added_es_ja:es.length-JSON.parse(base.exercise_ids_es_ja_json||'[]').length});const session={...base,session_id:id,planned_ja_es:base.planned_ja_es||settings.dailyJaEs,planned_es_ja:base.planned_es_ja||settings.dailyEsJa,exercise_ids_ja_es_json:JSON.stringify(ja),exercise_ids_es_ja_json:JSON.stringify(es),status:'in_progress',completed_at:null,selection_reason_json:JSON.stringify({...JSON.parse(base.selection_reason_json||'{}'),extra_extension:'same_day_small_extension_v1'}),extra_study_history_json:JSON.stringify(history)};await JapoDB.put('daily_sessions',session);return session}
  async function replaceExercise(session,exerciseId,reason,settings){
    const [exercises,progress,attempts]=await Promise.all([JapoDB.all('exercises'),JapoDB.all('exercise_progress'),JapoDB.all('attempts')]),current=exercises.find(exercise=>exercise.exercise_id===exerciseId);if(!current)return null;
    const completed=new Set(JSON.parse(session.completed_exercise_ids_json||'[]')),planned=new Set([...(JSON.parse(session.exercise_ids_ja_es_json||'[]')),...(JSON.parse(session.exercise_ids_es_ja_json||'[]'))]),gates=difficultyRoadmap(exercises,attempts,current.direction),unlocked=(gates[current.jlpt_level]?.unlockedBand)??0,currentScore=Difficulty.score(current),recent=new Set(validAttempts(attempts).filter(attempt=>attempt.direction===current.direction).sort((left,right)=>String(right.attempted_at).localeCompare(String(left.attempted_at))).slice(0,12).map(attempt=>attempt.exercise_id));
    const candidates=exercises.filter(exercise=>exercise.active!==false&&exercise.direction===current.direction&&exercise.exercise_id!==exerciseId&&!completed.has(exercise.exercise_id)&&Difficulty.bandFor(exercise)<=((gates[exercise.jlpt_level]?.unlockedBand)??0));
    const levelCandidates=candidates.filter(exercise=>exercise.jlpt_level===current.jlpt_level),pool=levelCandidates.length?levelCandidates:candidates;
    const scored=pool.map(exercise=>{const distance=Math.abs(Difficulty.score(exercise)-currentScore),recentPenalty=recent.has(exercise.exercise_id)?70:0,plannedPenalty=planned.has(exercise.exercise_id)?25:0;let preference=0;if(reason==='too_hard')preference=Difficulty.score(exercise)<=currentScore?80:0;if(reason==='too_easy')preference=Difficulty.score(exercise)>=currentScore?80:0;if(reason==='recent')preference=recent.has(exercise.exercise_id)?-120:40;return {exercise,score:preference-distance-recentPenalty-plannedPenalty+hash(`${session.session_id}:${reason}:${exercise.exercise_id}`)%17}}).sort((left,right)=>right.score-left.score);
    const replacement=scored[0]?.exercise;if(!replacement)return null;const field=current.direction==='ja_es'?'exercise_ids_ja_es_json':'exercise_ids_es_ja_json',ids=JSON.parse(session[field]||'[]'),index=ids.indexOf(exerciseId),nextIds=index<0?[replacement.exercise_id,...ids.filter(id=>id!==replacement.exercise_id)]:ids.map(id=>id===exerciseId?replacement.exercise_id:id),history=JSON.parse(session.replacement_history_json||'[]');history.push({from:exerciseId,to:replacement.exercise_id,reason,at:new Date().toISOString()});const next={...session,[field]:JSON.stringify(nextIds),replacement_history_json:JSON.stringify(history)};await JapoDB.put('daily_sessions',next);return {session:next,exerciseId:replacement.exercise_id,previousId:exerciseId};
  }
  window.SessionPlanner={localDate,getOrCreate,createExtra,choose,difficultyRoadmap,replaceExercise};
})();
