(function(){
  const labels={translation_attempt:'Traducciones',daily_news_answer:'Comprensión de noticias',news_reading:'Lecturas graduadas',lens_analysis:'Análisis con lupa'};
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const typeOf=attempt=>attempt.study_event_type||'translation_attempt';
  const dateKey=value=>String(value||'').slice(0,10);
  const format=value=>new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}).format(Number(value)||0);
  function familyFor(attempt,exercise){const topics=attempt.topic_tags||exercise?.topic_tags||[];return window.TopicProgression?.familyFor?.(topics[0]||'')||'Conocimiento y consultas'}
  function model(snapshot,ranked,filter='all'){
    const now=Date.now(),since=now-7*86400000,attempts=snapshot.attempts.filter(item=>item.study_event_type!=='lexical_review'&&(filter==='all'||item.direction===filter)&&Date.parse(item.attempted_at)>=since),ledger=RankedProgress.history(snapshot.exercises,snapshot.attempts).filter(item=>item.study_event_type!=='lexical_review'&&(filter==='all'||item.direction===filter)&&Date.parse(item.attempted_at)>=since),ledgerById=new Map(ledger.map(item=>[item.attempt_id,item])),exerciseById=snapshot.eMap||new Map(snapshot.exercises.map(item=>[item.exercise_id,item])),activities=new Map(),families=new Map(),uniqueExercises=new Set(),uniqueTerms=new Set(),days=new Set();
    for(const attempt of attempts){const type=typeOf(attempt),row=activities.get(type)||{type,count:0,scoreCount:0,scoreTotal:0,xp:0};row.count++;row.scoreCount++;row.scoreTotal+=Number(attempt.overall_score)||0;row.xp+=Number(ledgerById.get(attempt.attempt_id)?.delta)||0;activities.set(type,row);days.add(dateKey(attempt.attempted_at));uniqueExercises.add(attempt.exercise_id);const exercise=exerciseById.get(attempt.exercise_id),family=familyFor(attempt,exercise),familyRow=families.get(family)||{family,count:0,total:0};familyRow.count++;familyRow.total+=Number(attempt.overall_score)||0;families.set(family,familyRow);for(const term of attempt.vocabulary_tags||exercise?.vocabulary_tags||[])uniqueTerms.add(term)}
    const passive=[...(snapshot.newsArticles||[]).map(item=>({type:'news_reading',at:item.saved_at||item.created_at})),...(snapshot.lensCaptures||[]).map(item=>({type:'lens_analysis',at:item.created_at}))].filter(item=>Date.parse(item.at)>=since);for(const item of passive){const row=activities.get(item.type)||{type:item.type,count:0,scoreCount:0,scoreTotal:0,xp:0};row.count++;activities.set(item.type,row);days.add(dateKey(item.at))}
    const familyRows=[...families.values()].map(item=>({...item,average:Math.round(item.total/Math.max(1,item.count))})).sort((a,b)=>a.average-b.average||a.count-b.count),weak=familyRows[0],activeDays=days.size,activeAttemptIds=new Set(attempts.map(item=>item.attempt_id)),totalXp=ledger.filter(item=>activeAttemptIds.has(item.attempt_id)).reduce((sum,item)=>sum+Number(item.delta||0),0),total=attempts.length;
    const directions=filter==='all'?['ja_es','es_ja']:[filter],route=directions.map(direction=>{const rating=RankedProgress.primaryForDirection(ranked,direction);return {direction,level:rating.level,points:rating.points,goal:rating.goal}});
    const recommendation=!total?'Empieza una sesión para construir evidencia.':weak?`La próxima sesión priorizará ${weak.family}: ${weak.average}% en ${weak.count} evidencias esta semana.`:'La próxima sesión combinará material nuevo, recuperación espaciada y transferencia léxica.';
    return {attempts:total,activeDays,totalXp,uniqueExercises:uniqueExercises.size,uniqueTerms:uniqueTerms.size,activities:[...activities.values()].map(item=>({...item,average:item.scoreCount?Math.round(item.scoreTotal/item.scoreCount):null})),families:familyRows,route,recommendation};
  }
  function render(snapshot,ranked,filter='all'){
    const root=document.querySelector('#studySummary');if(!root)return;const data=model(snapshot,ranked,filter),activityHtml=data.activities.length?data.activities.map(item=>`<div class="study-activity"><span>${esc(labels[item.type]||item.type)}</span><strong>${item.count}</strong><small>${item.average==null?'Actividad registrada · no altera el rango':`${item.average}% medio · ${item.xp>=0?'+':''}${format(item.xp)} EXP`}</small></div>`).join(''):'<p class="empty">Aún no hay actividad registrada en los últimos siete días.</p>',routeHtml=data.route.map(item=>`<span><b>${item.direction==='ja_es'?'JP → ES':'ES → JP'}</b>${item.level} ${format(item.points)}/${format(item.goal)}</span>`).join('');root.innerHTML=`<header class="section-heading"><div><p class="section-kicker">Últimos 7 días</p><h3>Todo lo que has estudiado</h3></div><span class="metric-small">${data.activeDays}/7 días activos</span></header><div class="study-summary-metrics"><span><b>${data.attempts}</b> acciones evaluadas</span><span><b>${data.uniqueExercises}</b> ejercicios distintos</span><span><b>${data.uniqueTerms}</b> términos trabajados</span><span><b>${data.totalXp>=0?'+':''}${format(data.totalXp)}</b> EXP neta</span></div><div class="study-summary-body"><div class="study-activity-list">${activityHtml}</div><aside><p class="section-kicker">Plan guiado</p><strong>${esc(data.recommendation)}</strong><div class="study-route">${routeHtml}</div><small>Las lecturas y la lupa quedan registradas como estudio; solo las respuestas evaluadas demuestran dominio y mueven el rango.</small></aside></div>`;
  }
  window.StudySummary={model,render};
})();
