(function(){
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  document.addEventListener('DOMContentLoaded',()=>{
    const roadmap=document.querySelector('#topicRoadmap'),modal=document.querySelector('#topicDrillDetail'),list=document.querySelector('#topicDrillList'),title=document.querySelector('#topicDrillTitle'),summary=document.querySelector('#topicDrillSummary');
    roadmap.addEventListener('click',async event=>{const step=event.target.closest('.level-step[data-topic]');if(!step)return;const topic=step.dataset.topic,level=step.dataset.level,[exercises,attempts]=await Promise.all([JapoDB.all('exercises'),JapoDB.all('attempts')]),seen=new Set(attempts.map(a=>a.exercise_id)),matching=exercises.filter(e=>e.active!==false&&e.jlpt_level===level&&(e.topic_tags||[]).includes(topic));title.textContent=`${topic} · ${level}`;summary.textContent=`${matching.filter(e=>seen.has(e.exercise_id)).length} de ${matching.length} frases vistas. Elige cualquiera para practicarla ahora.`;list.innerHTML=matching.map((exercise,index)=>`<button class="exercise-choice ${seen.has(exercise.exercise_id)?'completed':''}" data-topic="${esc(topic)}" data-level="${level}" data-exercise-id="${exercise.exercise_id}"><span class="choice-index">${seen.has(exercise.exercise_id)?'✓':index+1}</span><span><strong>${esc(exercise.source_text)}</strong><small>${UI.directionName(exercise.direction)}</small></span><em>${seen.has(exercise.exercise_id)?'Repetir':'Resolver'} →</em></button>`).join('');modal.hidden=false});
    list.addEventListener('click',async event=>{const button=event.target.closest('[data-exercise-id]');if(!button)return;button.disabled=true;await window.JapoStartTopicDrill(button.dataset.topic,button.dataset.level,button.dataset.exerciseId);modal.hidden=true});
    document.querySelector('#closeTopicDrill').addEventListener('click',()=>modal.hidden=true);modal.addEventListener('click',event=>{if(event.target===modal)modal.hidden=true});
  });
})();
