(function(){
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  function toast(message){const e=$('#toast');e.textContent=message;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
  function showView(name){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$('#viewTitle').textContent={hoy:'Hoy',practicar:'Practicar',progreso:'Progreso',ajustes:'Ajustes'}[name];location.hash=name;if(name==='progreso')window.App.renderProgress();if(name==='ajustes')window.App.renderSettings();document.dispatchEvent(new CustomEvent('japoteacher:navigate',{detail:{view:name}}));scrollTo(0,0)}
  function directionName(d){return d==='ja_es'?'Japonés → Español':'Español → Japonés'}
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function japaneseWithFurigana(sentence,readings=[]){const items=[...readings].filter(x=>x.characters&&x.reading_hiragana).sort((a,b)=>b.characters.length-a.characters.length);let html='',index=0;while(index<sentence.length){const item=items.find(x=>sentence.startsWith(x.characters,index));if(item){html+=`<ruby>${esc(item.characters)}<rt>${esc(item.reading_hiragana)}</rt></ruby>`;index+=item.characters.length}else{html+=esc(sentence[index]);index++}}return html}
  function scoreRows(ev){return [['Significado',ev.objective_score],['Comprensión',ev.comprehensibility_score],['Naturalidad',ev.naturalness_score],['Gramática',ev.grammar_score],['Vocabulario',ev.vocabulary_score],['Ortografía',ev.orthography_score],['Registro',ev.register_score]].map(([n,v])=>`<div class="score-row"><span>${n}</span><div class="mini-bar"><span style="width:${v}%"></span></div><strong>${v}</strong></div>`).join('')}
  function feedback(ev,userAnswer='',options={}){
    const errors=Array.isArray(ev.errors)?ev.errors:[],strengths=Array.isArray(ev.strengths)?ev.strengths:[],readings=Array.isArray(ev.kanji_readings)?ev.kanji_readings:[],showNext=options.showNext!==false,japanese=ev.correct_japanese_sentence||'—';
    const comparisons=errors.length?errors.map(error=>`<article class="comparison-item"><div><span>Tu fragmento</span><strong>${esc(error.source_span||userAnswer||'—')}</strong></div><div class="comparison-arrow">→</div><div><span>Propuesta</span><strong>${esc(error.corrected_span||ev.natural_answer||'—')}</strong></div><p>${esc(error.explanation_es||'')}</p></article>`).join(''):`<article class="comparison-item comparison-ok"><p>Tu respuesta conserva correctamente el significado. No se detectaron cambios necesarios.</p></article>`;
    const unavailable=/[\u3400-\u9fff]/.test(japanese)?'Las lecturas detalladas no estaban disponibles en esta evaluación.':'Esta frase no contiene kanji que necesiten explicación.';
    const kanji=readings.length?readings.map(item=>`<article class="kanji-reading"><div><strong>${esc(item.characters)}</strong><span>${esc(item.reading_hiragana)}</span></div><p><b>${esc(item.meaning_es)}</b> · ${esc(item.explanation_es)}</p></article>`).join(''):`<p class="empty">${unavailable}</p>`;
    return `<div class="score-hero"><div class="score-ring" style="--score:${ev.overall_score}%"><strong>${ev.overall_score}%</strong></div><div><h3>${ev.is_acceptable?'¡Buen trabajo!':'Sigue practicando'}</h3><p>${ev.is_acceptable?'Respuesta aceptable':'Conviene revisar la respuesta'}</p></div></div><section class="proposed-translation"><span>Esta es la traducción propuesta</span><strong>${esc(ev.natural_answer||ev.corrected_answer||'—')}</strong><p>${esc(ev.explanation_es||'')}</p></section><section class="correct-japanese"><span>Esta es la frase correcta en japonés</span><div class="correct-japanese-text" lang="ja">${japaneseWithFurigana(japanese,readings)}</div><div class="kanji-reading-list">${kanji}</div></section><section class="answer-comparison"><h4>Comparación con tu respuesta</h4><div class="your-full-answer"><span>Lo que escribiste</span><strong>${esc(userAnswer||'—')}</strong></div>${comparisons}</section><div class="score-list">${scoreRows(ev)}</div>${strengths.length?`<p class="status-good"><strong>Aciertos:</strong> ${strengths.map(esc).join(', ')}</p>`:''}${showNext?'<button class="primary feedback-next" id="nextExerciseButton">Siguiente ejercicio</button>':''}`
  }
  window.UI={$, $$,toast,showView,directionName,feedback};
})();
