(function(){
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  function toast(message){const e=$('#toast');e.textContent=message;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
  async function showView(name){const loader=$('#routeLoader');loader?.classList.add('active');loader?.setAttribute('aria-hidden','false');$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));$$('.nav-item').forEach(x=>{const active=x.dataset.view===name;x.classList.toggle('active',active);x.toggleAttribute('aria-current',active)});$('#viewTitle').textContent={hoy:'Hoy',practicar:'Practicar',tutor:'Tutor IA',lupa:'Lupa IA',noticia:'Noticia del día',progreso:'Progreso',ajustes:'Ajustes'}[name]||'Hoy';location.hash=name;const work=name==='progreso'?window.App.renderProgress():name==='ajustes'?window.App.renderSettings():Promise.resolve();document.dispatchEvent(new CustomEvent('japoteacher:navigate',{detail:{view:name}}));scrollTo(0,0);await work;loader?.classList.remove('active');loader?.setAttribute('aria-hidden','true')}
  function directionName(d){return d==='ja_es'?'Japonés → Español':'Español → Japonés'}
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function japaneseWithFurigana(sentence,readings=[]){const items=[...readings].filter(x=>x.characters&&x.reading_hiragana).sort((a,b)=>b.characters.length-a.characters.length);let html='',index=0;while(index<sentence.length){const item=items.find(x=>sentence.startsWith(x.characters,index));if(item){html+=`<ruby>${esc(item.characters)}<rt>${esc(item.reading_hiragana)}</rt></ruby>`;index+=item.characters.length}else{html+=esc(sentence[index]);index++}}return html}
  function scoreRows(ev){return [['Significado',ev.objective_score],['Comprensión',ev.comprehensibility_score],['Naturalidad',ev.naturalness_score],['Gramática',ev.grammar_score],['Vocabulario',ev.vocabulary_score],['Ortografía',ev.orthography_score],['Registro',ev.register_score]].map(([n,v])=>`<div class="score-row"><span>${n}</span><div class="mini-bar"><span style="width:${v}%"></span></div><strong>${v}</strong></div>`).join('')}
  function annotatedText(value,readings=[]){const text=String(value??'');return /[\u3400-\u9fff]/.test(text)?japaneseWithFurigana(text,readings):esc(text)}
  function comparableFragment(value){return String(value??'').normalize('NFKC').replace(/<[^>]*>/g,'').replace(/[\s\u3000。、，,.!?！？¿¡「」『』（）()[\]{}・･"'`´]/g,'').toLocaleLowerCase('es')}
  function sameFragment(a,b){const left=comparableFragment(a),right=comparableFragment(b);return Boolean(left&&right&&left===right)}
  function usageFor(reading,exercise){if(window.FeedbackVocabulary)return window.FeedbackVocabulary.resolve(reading,exercise);const items=(Array.isArray(exercise?.usage_components)?exercise.usage_components:[]).filter(item=>item.k==='v'),value=String(reading?.characters||''),exact=items.find(item=>item.t===value);if(exact)return[exact];return items.filter(item=>item.t&&value.includes(item.t)).sort((a,b)=>value.indexOf(a.t)-value.indexOf(b.t)||b.t.length-a.t.length)}
  function usageBadge(items){return (Array.isArray(items)?items:items?[items]:[]).filter(item=>item.p!=null&&item.p!==''&&Number.isFinite(Number(item.p))).map(item=>{const value=Number(item.p),display=value<1?value.toFixed(2):value.toFixed(1),dialogue=item.de==='web_prior'?'diálogo estimado':'diálogo observado',details=item.w==null?'':`Web: top ${Number(item.w).toFixed(1)}% · ${dialogue}: ${Math.round(Number(item.d))}/100 · dispersión: ${Math.round(Number(item.x))}/100`;return `<em class="usage-rank-badge" title="${esc(details)}">${esc(item.t)} · uso combinado top ${display}% · ${esc(item.l)}</em>`}).join('')||'<em class="usage-rank-badge">Sin ranking disponible</em>'}
  function feedback(ev,userAnswer='',options={}){
    const errors=Array.isArray(ev.errors)?ev.errors:[],strengths=Array.isArray(ev.strengths)?ev.strengths:[],readings=Array.isArray(ev.kanji_readings)?ev.kanji_readings:[],showNext=options.showNext!==false,japanese=ev.correct_japanese_sentence||'—',proposalFromEvaluation=ev.natural_answer||ev.corrected_answer||'',isJapaneseToSpanish=options.direction==='ja_es'||(!options.direction&&!/[\u3400-\u9fff]/.test(userAnswer)&&!/[\u3400-\u9fff]/.test(proposalFromEvaluation)&&/[\u3400-\u9fff]/.test(japanese)),referenceTranslation=options.exercise?.reference_translation||'';
    const visibleErrors=errors.filter(error=>!sameFragment(error.source_span||'',error.corrected_span||''));
    const support=window.FeedbackVocabulary?.prepare(japanese,readings,options.exercise)||{text:japanese,readings:readings.filter(item=>japanese.includes(item.characters))};
    const comparisons=visibleErrors.length?visibleErrors.map(error=>{const source=error.source_span||userAnswer||'—',correction=error.corrected_span||ev.natural_answer||'—';return `<article class="comparison-item"><div><span>Tu fragmento</span><strong${/[\u3400-\u9fff]/.test(source)?' lang="ja"':''}>${annotatedText(source,readings)}</strong></div><div class="comparison-arrow">→</div><div><span>Propuesta</span><strong${/[\u3400-\u9fff]/.test(correction)?' lang="ja"':''}>${annotatedText(correction,readings)}</strong></div><p>${esc(error.explanation_es||'')}</p></article>`}).join(''):`<article class="comparison-item comparison-ok"><p>Tu respuesta conserva correctamente el significado. No se detectaron cambios necesarios.</p></article>`;
    const unavailable=/[\u3400-\u9fff]/.test(japanese)?'Las lecturas detalladas no estaban disponibles en esta evaluación.':'Esta frase no contiene kanji que necesiten explicación.';
    const kanji=support.readings.length?support.readings.map(item=>`<article class="kanji-reading"><div><strong>${esc(item.characters)}</strong><span>${esc(item.reading_hiragana)}</span>${usageBadge(usageFor(item,options.exercise))}</div>${item.meaning_es||item.explanation_es?`<p><b>${esc(item.meaning_es)}</b>${item.meaning_es&&item.explanation_es?' · ':''}${esc(item.explanation_es)}</p>`:''}</article>`).join(''):`<p class="empty">${unavailable}</p>`;
    const proposal=isJapaneseToSpanish?referenceTranslation||proposalFromEvaluation||'—':window.FeedbackVocabulary?.canonical(proposalFromEvaluation)||proposalFromEvaluation||'—';
    const japaneseSupport=isJapaneseToSpanish&&support.readings.length?`<section class="correct-japanese"><span>Palabras clave del enunciado</span><div class="kanji-reading-list">${kanji}</div></section>`:isJapaneseToSpanish?'':`<section class="correct-japanese"><span>Esta es la frase correcta en japonés</span><div class="correct-japanese-text" lang="ja">${japaneseWithFurigana(support.text,support.readings)}</div><div class="kanji-reading-list">${kanji}</div></section>`;
    return `<div class="score-hero"><div class="score-ring" style="--score:${ev.overall_score}%"><strong>${ev.overall_score}%</strong></div><div><h3>${ev.is_acceptable?'¡Buen trabajo!':'Sigue practicando'}</h3><p>${ev.is_acceptable?'Respuesta aceptable':'Conviene revisar la respuesta'}</p></div></div><section class="proposed-translation"><span>Traducción de referencia · respuesta modelo</span><strong${/[\u3400-\u9fff]/.test(proposal)?' lang="ja"':''}>${annotatedText(proposal,isJapaneseToSpanish?readings:support.readings)}</strong><p>${esc(ev.explanation_es||'')}</p></section>${japaneseSupport}<section class="answer-comparison"><h4>Comparación con tu respuesta</h4><div class="your-full-answer"><span>Lo que escribiste</span><strong>${esc(userAnswer||'—')}</strong></div>${comparisons}</section><div class="score-list">${scoreRows(ev)}</div>${strengths.length?`<p class="status-good"><strong>Aciertos:</strong> ${strengths.map(esc).join(', ')}</p>`:''}${showNext?'<button class="primary feedback-next" id="nextExerciseButton">Siguiente ejercicio</button>':''}`
  }
  window.UI={$, $$,toast,showView,directionName,feedback,japaneseWithFurigana};
})();
